### PR TITLE
enable extractps test case

### PR DESCRIPTION
**Pull request by dannypsnl**
@mewmew add this file and later update [PR](https://github.com/llir/llvm/pull/127) like [this commit](https://github.com/llir/llvm/commit/0783e7c14d081914acda0c0c8481f30d73c8ee02) right?

related to https://github.com/llir/llvm/issues/118

### CODE REVIEW

**Review by mewmew — CHANGES_REQUESTED** [review]
Good that you added the golden test case @dannypsnl.

Just a few things to make the test pass. The *golden* test case is essentially the expected output of llir/llvm. As such, instead of @"", we will output the explicit global ID. Same as we do for local variables.

So, the expected output of llir/llvm (and thus the contents of `extractps.ll.golden`) is as follows:

```llvm
@0 = external global float, align 16

define internal void @1() nounwind {
; <label>:0
	%1 = load float, float* @0, align 16
	%2 = insertelement <4 x float> undef, float %1, i32 0
	%3 = call <4 x float> @llvm.x86.sse.rsqrt.ss(<4 x float> %2)
	%4 = extractelement <4 x float> %3, i32 0
	store float %4, float* @0, align 16
	ret void
}

define internal void @2() nounwind {
; <label>:0
	%1 = load float, float* @0, align 16
	%2 = insertelement <4 x float> undef, float %1, i32 1
	%3 = call <4 x float> @llvm.x86.sse.rsqrt.ss(<4 x float> %2)
	%4 = extractelement <4 x float> %3, i32 1
	store float %4, float* @0, align 16
	ret void
}

declare <4 x float> @llvm.x86.sse.rsqrt.ss(<4 x float>) nounwind readnone
```

**Comment by mewmew** [comment]
> @mewmew add this file and later update PR like this commit right?

Exactly. Once this PR is merged (after updating the golden test), then we just need to update the `testdata` submodule of the `llir/llvm` repo to the latest commit. After that the tests cases of #118 should be passing.

**Comment by dannypsnl** [comment]
> Good that you added the golden test case @dannypsnl.
> 
> Just a few things to make the test pass. The _golden_ test case is essentially the expected output of llir/llvm. As such, instead of @"", we will output the explicit global ID. Same as we do for local variables.
> 
> So, the expected output of llir/llvm (and thus the contents of `extractps.ll.golden`) is as follows:
> 
> ```llvm
> @0 = external global float, align 16
> 
> define internal void @1() nounwind {
> ; <label>:0
> 	%1 = load float, float* @0, align 16
> 	%2 = insertelement <4 x float> undef, float %1, i32 0
> 	%3 = call <4 x float> @llvm.x86.sse.rsqrt.ss(<4 x float> %2)
> 	%4 = extractelement <4 x float> %3, i32 0
> 	store float %4, float* @0, align 16
> 	ret void
> }
> 
> define internal void @2() nounwind {
> ; <label>:0
> 	%1 = load float, float* @0, align 16
> 	%2 = insertelement <4 x float> undef, float %1, i32 1
> 	%3 = call <4 x float> @llvm.x86.sse.rsqrt.ss(<4 x float> %2)
> 	%4 = extractelement <4 x float> %3, i32 1
> 	store float %4, float* @0, align 16
> 	ret void
> }
> 
> declare <4 x float> @llvm.x86.sse.rsqrt.ss(<4 x float>) nounwind readnone
> ```

Just update and tested.

**Comment by mewmew** [comment]
> Just update and tested.

Great. Did you push the latest update? (I still see `@""` in the PR, instead of `@1`).

**Comment by dannypsnl** [comment]
> > Just update and tested.
> 
> Great. Did you push the latest update? (I still see `@""` in the PR, instead of `@1`).

I pushed to this repo www.

**Review by mewmew — APPROVED** [review]
LGTM.

**Pull request merged**
